import test from 'node:test';
import assert from 'node:assert/strict';
import {SocialStore} from '../server/social.js';
import {SocialUI} from '../client/social-ui.js';
import {UI} from '../client/ui.js';

const person=(n,online=false)=>({id:`player-${String(n).padStart(6,'0')}`,username:`Player_${String(n).padStart(2,'0')}`,createdAt:1,online,status:online?'online':'offline',email:'private@example.test',passwordHash:'private-hash'});
function directory(){const store=Object.assign(Object.create(SocialStore.prototype),{friends:new Map(),requests:new Map()});const users=Array.from({length:54},(_,i)=>person(i));return {store,users,auth:{users:new Map(users.map(u=>[u.username,u]))}};}
function view(){const user=person(0,true),friend=person(1,true),offline=person(2);const social=Object.assign(Object.create(SocialUI.prototype),{busy:false,tab:'directory',query:'',directoryLoading:false,searchMessage:'',directory:{users:[],total:0,offset:0,limit:24,hasMore:false},network:{status:'connected',social:{friends:[friend,offline],incoming:[],outgoing:[],invites:[]},party:{leaderId:user.id,status:'idle',members:[user],maxSize:4}},ui:{auth:{user},game:{active:false}}});return {social,user,friend,offline};}

test('global directory paginates every other account exactly once and only returns public fields',()=>{const {store,users,auth}=directory();const seen=[];for(let offset=0;offset<53;offset+=24){const d=store.directory('',offset,24,users[0].id,auth,()=> 'offline');assert.equal(d.total,53);assert.ok(d.users.length<=24);for(const p of d.users){assert.equal(p.email,undefined);assert.equal(p.passwordHash,undefined);assert.equal(p.online,false);seen.push(p.id);}}assert.equal(seen.length,53);assert.equal(new Set(seen).size,53);assert.ok(!seen.includes(users[0].id));});
test('directory supports case-insensitive game names, exact matches and bounded validated arguments',()=>{const {store,users,auth}=directory();assert.equal(store.directory('pLaYeR_12',0,24,users[0].id,auth).users[0].id,users[12].id);assert.equal(store.directory('notfound',0,24,users[0].id,auth).total,0);for(const [q,o,l]of [[{},0,24],['x'.repeat(19),0,24],['',-1,24],['',.5,24],['',0,1000],['',0,0]])assert.throws(()=>store.directory(q,o,l,users[0].id,auth));});
test('Quick Play keeps every accepted friend including offline profiles and does not cap the list at four',()=>{const {social}=view();social.network.social.friends=Array.from({length:12},(_,i)=>person(i+1,i%2===0));const html=social.friendsHTML();assert.equal((html.match(/data-friend-id=/g)||[]).length,12);assert.match(html,/OFFLINE/);assert.match(html,/ONLINE/);assert.equal((html.match(/INVITE TO LOBBY/g)||[]).length,12);assert.match(html,/title="Player is offline" disabled/);});
test('invite enablement preserves online, leader, match and capacity rules',()=>{const {social,friend,offline}=view();assert.equal(social.inviteReason(friend),'');assert.match(social.inviteReason(offline),/offline/);friend.status='in_match';assert.match(social.inviteReason(friend),/busy/);friend.status='online';social.network.party.leaderId='someone-else';assert.match(social.inviteReason(friend),/leader/);social.network.party.leaderId=social.self;social.network.party.members=Array.from({length:4},(_,n)=>person(n));assert.match(social.inviteReason(friend),/full/);});
test('Pending shows recipient-owned accept/cancel and sender-owned cancellation controls',()=>{const {social,friend,offline}=view();social.tab='pending';social.network.social.incoming=[{id:'request-in',from:friend}];social.network.social.outgoing=[{id:'request-out',to:offline}];const html=social.socialHTML();assert.match(html,/data-social="accept-friend" data-request="request-in"/);assert.match(html,/data-social="decline-friend" data-request="request-in"/);assert.match(html,/data-social="cancel-friend" data-request="request-out"/);});
test('player cards escape public strings and show requests rather than adding twice',()=>{const {social,friend}=view();friend.username='<img src=x onerror=alert(1)>';const card=social.playerCard(friend);assert.ok(!card.includes('<img'));assert.match(card,/&lt;img/);assert.match(card,/✓ FRIENDS/);assert.ok(!card.includes('data-social="add-friend"'));});
test('unchanged queue heartbeats do not replace the home DOM or rerun editor setup',async()=>{let renders=0,editor=0;const oldDocument=globalThis.document;globalThis.document={getElementById(){return null;}};try{const ui=Object.assign(Object.create(UI.prototype),{current:'play',game:{active:false},editorState:{open:false},network:{party:{id:'p',status:'queued'},queue:{mode:'tdm',startedAt:1,playersSearching:1},social:{friends:[]}},store:{data:{mode:'tdm',operator:'sentinel',loadout:['ar4','relay9','edge']}},page:{scrollTop:29,querySelector(){return null;},set innerHTML(v){renders++;}},home(){return 'home';},prepareEditorTargets(){editor++;},hydrateOperatorPortraits(){}});ui.updateQuickQueue();await Promise.resolve();assert.equal(renders,1);for(let n=0;n<20;n++){ui.network.queue.playersSearching=n;ui.updateQuickQueue();await Promise.resolve();}assert.equal(renders,1);assert.equal(editor,1);assert.equal(ui.page.scrollTop,29);ui.network.party.status='idle';ui.network.queue=null;ui.updateQuickQueue();await Promise.resolve();assert.equal(renders,2);}finally{globalThis.document=oldDocument;}});
