import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import WebSocket from 'ws';
import {createGameServer} from '../server/server.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,timeout=3500){const end=Date.now()+timeout;while(Date.now()<end){const result=fn();if(result)return result;await delay(10);}throw Error('Timed out waiting for condition');}
async function next(c,predicate){return until(()=>{const i=c.events.findIndex(predicate);return i<0?null:c.events.splice(i,1)[0];});}
async function fixture(t,options={}){const dataDir=await mkdtemp(join(tmpdir(),'hamu-social-e2e-')),app=createGameServer({dataDir,queueWaitMs:400,matchmakingIntervalMs:20,...options,migrateLegacy:false});const addr=await app.start({port:0,host:'127.0.0.1'});const clients=[];t.after(async()=>{for(const c of clients)c.ws.terminate();await app.close();await rm(dataDir,{recursive:true,force:true});});
 async function connect(name,existing){const user=existing?.user||await app.auth.register(name,`${name.toLowerCase()}@example.test`,'Integration-password-77');const session=await app.auth.login(user.username,'Integration-password-77');const ws=new WebSocket(`ws://127.0.0.1:${addr.port}/ws`,{headers:{Cookie:`hamu_session=${session.token}`}});const c={user,ws,events:[],state:{},serial:0};clients.push(c);ws.on('message',raw=>{const data=JSON.parse(raw);c.events.push(data);c.state[data.t]=data;});await next(c,x=>x.t==='hello');await until(()=>c.state.party_state?.party&&c.state.social_state);c.rpc=async(op,fields={})=>{const requestId=String(++c.serial);ws.send(JSON.stringify({...fields,t:op,requestId}));const result=await next(c,x=>x.t==='reply'&&x.requestId===requestId);if(!result.ok)throw Error(result.error);return result.result;};return c;}
 return{app,connect};}
async function friends(a,b){await a.rpc('social.request',{userId:b.user.id});await until(()=>b.state.social_state.incoming.some(x=>x.from.id===a.user.id));const r=b.state.social_state.incoming.find(x=>x.from.id===a.user.id);await b.rpc('social.respond',{friendRequestId:r.id,accept:true});await until(()=>a.state.social_state.friends.some(x=>x.id===b.user.id));}
async function invite(a,b){await a.rpc('party.invite',{userId:b.user.id});const i=await until(()=>b.state.social_state.invites.find(x=>x.from.id===a.user.id));await b.rpc('party.inviteRespond',{inviteId:i.id,accept:true});await until(()=>b.state.party_state.party.members.length>1);}

test('live friend requests cancel on both sides, presence updates, and reconnect does not leave an offline party',async t=>{const{app,connect}=await fixture(t);const a=await connect('LiveAlpha'),b=await connect('LiveBravo'),c=await connect('LiveCharlie');
 await a.rpc('social.request',{userId:b.user.id});const r=await until(()=>b.state.social_state.incoming[0]);await assert.rejects(c.rpc('social.respond',{friendRequestId:r.id,accept:true}));await a.rpc('social.cancel',{friendRequestId:r.id});await until(()=>b.state.social_state.incoming.length===0);
 await friends(a,b);b.ws.close();await until(()=>a.state.social_state.friends.find(x=>x.id===b.user.id)?.status==='offline');const b2=await connect(null,b);await until(()=>a.state.social_state.friends.find(x=>x.id===b.user.id)?.status==='online');assert.equal(app.matchmaking.partyFor(b.user.id).members[0].online,true);
 await b2.rpc('queue.join',{});await until(()=>a.state.social_state.friends.find(x=>x.id===b.user.id)?.status==='queued');await b2.rpc('queue.cancel');
});

test('real party leader/ready gate, automatic invite readiness, guest cancellation, random-player queue, bot fill, and replacement after departure',async t=>{const{app,connect}=await fixture(t,{queueWaitMs:700});const a=await connect('SquadAlpha'),b=await connect('SquadBravo'),c=await connect('RandomCharlie'),d=await connect('RandomDelta');await friends(a,b);await invite(a,b);
 assert.equal(b.state.party_state.party.members.find(m=>m.id===b.user.id).ready,true);assert.equal(a.state.party_state.party.leaderId,a.user.id);await assert.rejects(b.rpc('queue.join',{}),/leader/i);await a.rpc('queue.join',{});await until(()=>b.state.queue_state?.queue);await b.rpc('party.ready',{ready:false});await until(()=>a.state.party_state.party.status==='idle');assert.equal(app.matchmaking.tickets.size,0);assert.equal(a.state.party_state.party.members.find(m=>m.id===b.user.id).ready,false);assert.equal(a.state.party_state.party.members.find(m=>m.id===a.user.id).ready,true);
 await b.rpc('party.ready',{ready:true});await a.rpc('queue.join',{});await c.rpc('queue.join',{});const aj=await next(a,x=>x.t==='joined'),bj=await next(b,x=>x.t==='joined'),cj=await next(c,x=>x.t==='joined');assert.equal(aj.room.id,bj.room.id);assert.equal(cj.room.id,aj.room.id);assert.equal(aj.state.players.length,8);const room=app.rooms.get(aj.room.id);assert.equal(room.clients.size,3);assert.equal([...room.world.players.values()].filter(p=>p.bot).length,5);assert.equal(room.world.players.get(aj.id).team,room.world.players.get(bj.id).team);assert.equal(app.matchmaking.partyFor(a.user.id).roomId,aj.room.id);
 b.ws.close();await until(()=>room.clients.size===2);await d.rpc('queue.join',{});const dj=await next(d,x=>x.t==='joined');assert.equal(dj.room.id,aj.room.id);assert.equal(room.world.players.size,8);assert.equal(room.clients.size,3);for(const team of[0,1])assert.equal([...room.world.players.values()].filter(p=>p.team===team).length,4);
});

test('party invites work for online players, auto-friend on acceptance, enforce recipient ownership and expiry',async t=>{const{connect}=await fixture(t,{inviteTtlMs:300});const a=await connect('InviteAlpha'),b=await connect('InviteBravo'),c=await connect('InviteCharlie');
 await a.rpc('party.invite',{userId:b.user.id});const invite=await until(()=>b.state.social_state.invites[0]);await assert.rejects(c.rpc('party.inviteRespond',{inviteId:invite.id,accept:true}));await assert.rejects(a.rpc('party.invite',{userId:b.user.id}));await b.rpc('party.inviteRespond',{inviteId:invite.id,accept:true});await until(()=>b.state.party_state.party.members.length>1);await until(()=>a.state.social_state.friends.some(x=>x.id===b.user.id));await until(()=>b.state.social_state.friends.some(x=>x.id===a.user.id));
 await a.rpc('party.leave');await b.rpc('party.leave');await a.rpc('party.invite',{userId:b.user.id});const second=await until(()=>b.state.social_state.invites[0]);await delay(350);await assert.rejects(b.rpc('party.inviteRespond',{inviteId:second.id,accept:true}));await until(()=>b.state.social_state.invites.length===0);
});

test('parties cap at four in every playlist, leader controls mode, and departure transfers leadership',async t=>{const{app,connect}=await fixture(t);const a=await connect('CapAlpha'),members=[];for(const name of['CapBravo','CapCharlie','CapDelta','CapEcho']){const c=await connect(name);members.push(c);await friends(a,c);}for(const c of members.slice(0,3))await invite(a,c);await assert.rejects(a.rpc('party.invite',{userId:members[3].user.id}),/full/i);await a.rpc('party.mode',{mode:'ffa'});await assert.rejects(members[0].rpc('party.mode',{mode:'tdm'}),/leader/i);const p=app.matchmaking.partyFor(a.user.id);assert.equal(p.maxSize,4);assert.equal(p.mode,'ffa');assert.equal(p.members.length,4);await a.rpc('party.leave');await until(()=>members[0].state.party_state.party.leaderId===members[0].user.id);const after=app.matchmaking.partyFor(members[0].user.id);assert.equal(after.members[0].ready,true);assert.equal(after.members.slice(1).every(m=>!m.ready),true);await assert.rejects(members[1].rpc('queue.join',{}),/leader/i);await members[0].rpc('party.kick',{userId:members[2].user.id});assert.equal(app.matchmaking.partyFor(members[2].user.id).members.length,1);});

test('late two-player party replaces two distinct bots, and ended rooms do not accept backfill',async t=>{const{app,connect}=await fixture(t,{queueWaitMs:80});const solo=await connect('FillSolo'),a=await connect('FillAlpha'),b=await connect('FillBravo'),late=await connect('FillLate');await friends(a,b);await invite(a,b);await b.rpc('party.ready',{ready:true});await solo.rpc('queue.join',{});const sj=await next(solo,x=>x.t==='joined');await a.rpc('queue.join',{});const aj=await next(a,x=>x.t==='joined'),bj=await next(b,x=>x.t==='joined');assert.equal(aj.room.id,sj.room.id);assert.equal(bj.room.id,sj.room.id);const room=app.rooms.get(sj.room.id);assert.equal(room.world.players.size,8);assert.equal([...room.world.players.values()].filter(p=>p.bot).length,5);assert.equal(room.world.players.get(aj.id).team,room.world.players.get(bj.id).team);for(const team of[0,1])assert.equal([...room.world.players.values()].filter(p=>p.team===team).length,4);room.world.finish(null);await late.rpc('queue.join',{});const lj=await next(late,x=>x.t==='joined');assert.notEqual(lj.room.id,sj.room.id);});

test('completed queued match returns the same squad to lobby and requires fresh member readiness',async t=>{const{app,connect}=await fixture(t,{queueWaitMs:60});const a=await connect('ReturnAlpha'),b=await connect('ReturnBravo');await friends(a,b);await invite(a,b);const partyId=app.matchmaking.partyFor(a.user.id).id;await b.rpc('party.ready',{ready:true});await a.rpc('queue.join',{});const joined=await next(a,x=>x.t==='joined');await next(b,x=>x.t==='joined');await assert.rejects(a.rpc('party.return'));const room=app.rooms.get(joined.room.id);room.world.finish(null);room.world.endedAt=room.world.time-12;app.tick();await next(a,x=>x.t==='party_return');await next(b,x=>x.t==='party_return');const p=app.matchmaking.partyFor(a.user.id);assert.equal(p.id,partyId);assert.equal(p.members.length,2);assert.equal(p.status,'idle');assert.equal(p.leaderId,a.user.id);assert.equal(p.members.find(m=>m.id===b.user.id).ready,false);assert.equal(app.rooms.size,0);assert.equal(app.matchmaking.matches.size,0);await assert.rejects(a.rpc('queue.join',{}),/ready/i);});

test('eight real queued FFA players start immediately, without bots or waiting for timeout',async t=>{const{app,connect}=await fixture(t,{queueWaitMs:60000});const users=[];for(let i=0;i<8;i++){const c=await connect(`FullMatch${i}`);users.push(c);await c.rpc('party.mode',{mode:'ffa'});}for(const c of users)await c.rpc('queue.join',{mode:'ffa'});const joined=await Promise.all(users.map(c=>next(c,x=>x.t==='joined')));assert.equal(new Set(joined.map(j=>j.room.id)).size,1);const room=app.rooms.get(joined[0].room.id);assert.equal(room.clients.size,8);assert.equal(room.world.players.size,8);assert.equal([...room.world.players.values()].some(p=>p.bot),false);assert.equal(app.matchmaking.tickets.size,0);});

test('replacement sockets cannot create duplicate players and custom room bot replacement stays within capacity',async t=>{const{app,connect}=await fixture(t);const a=await connect('SocketAlpha'),b=await connect('SocketBravo');a.ws.send(JSON.stringify({t:'create',mode:'tdm',bots:7}));const aj=await next(a,x=>x.t==='joined');b.ws.send(JSON.stringify({t:'join',room:aj.room.id}));const bj=await next(b,x=>x.t==='joined');assert.equal(bj.state.players.length,8);assert.equal(app.rooms.get(aj.room.id).clients.size,2);const a2=await connect(null,a);await until(()=>a.ws.readyState===WebSocket.CLOSED);assert.equal([...app.clients.values()].filter(c=>c.accountId===a.user.id).length,1);assert.equal(app.matchmaking.partyFor(a.user.id).members[0].online,true);await a2.rpc('queue.join',{});await a2.rpc('queue.cancel');
});
